FORMAT: 1A
HOST: http://172.31.19.85:8545

# API for Ethereum JSON RPC

## Postman
Postman helps you be more efficient while working with APIs. Using Postman, you can construct complex HTTP 
requests quickly, organize them in collections and share them with your co-workers. 
<a href="http://www.getpostman.com" target="_blank">Learn more</a>.

Try Django Ethereum RPC Connect API in Postman
 
<p><a href="/artifacts/postman.json"><img src="https://run.pstmn.io/button.svg" alt="Run in Postman"></a></p>
 

# Group Ethereum RPC API

<!-- include(account.md) -->